const API = 'http://localhost:5000/api';
let user = null, loginToken = null, regUserId = null, lockTimer = null;

async function api(url, opts = {}) {
    const t = localStorage.getItem('token') || loginToken;
    try { const r = await fetch(API + url, { headers: { 'Content-Type': 'application/json', ...(t ? { Authorization: 'Bearer ' + t } : {}), ...opts.headers }, ...opts }); return r.json() }
    catch (e) { return { success: false, error: 'Connection failed' } }
}
function toast(m, t = 'info') { const e = document.getElementById('toast'); e.textContent = m; e.className = 'show ' + t; setTimeout(() => e.className = '', 3000) }
function $(id) { return document.getElementById(id) }
function money(n) { return '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2 }) }

function showPage(p) { document.querySelectorAll('.page').forEach(x => x.classList.remove('active')); document.querySelectorAll('.nav-links a').forEach(a => a.classList.remove('active')); $(p)?.classList.add('active'); document.querySelector(`[data-page="${p}"]`)?.classList.add('active'); if (p === 'dashboard') loadDashboard() }
document.querySelectorAll('.nav-links a').forEach(a => { a.onclick = e => { e.preventDefault(); showPage(a.dataset.page) } });

function showAuth(t) { $('auth-modal').classList.remove('hidden'); $('login-view').classList.toggle('hidden', t !== 'login'); $('register-view').classList.toggle('hidden', t !== 'register'); $('login-form').classList.remove('hidden'); $('otp-view').classList.add('hidden'); $('register-form').classList.remove('hidden'); $('2fa-setup').classList.add('hidden') }
function closeAuth() { $('auth-modal').classList.add('hidden') }
function setupOTP(id) { const c = $(id); c.innerHTML = [0, 1, 2, 3, 4, 5].map(i => `<input type="text" maxlength="1">`).join(''); const inputs = c.querySelectorAll('input'); inputs.forEach((inp, i) => { inp.oninput = () => { if (inp.value && i < 5) inputs[i + 1].focus() }; inp.onkeydown = e => { if (e.key === 'Backspace' && !inp.value && i > 0) inputs[i - 1].focus() } }); return () => [...inputs].map(i => i.value).join('') }
let getLoginOTP, getSetupOTP;

$('login-form').onsubmit = async e => { e.preventDefault(); const res = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email: $('login-email').value, password: $('login-pass').value }) }); if (!res.success) return toast(res.error, 'error'); loginToken = res.login_token; $('login-form').classList.add('hidden'); $('otp-view').classList.remove('hidden'); getLoginOTP = setupOTP('login-otp') };
async function verifyLogin() { const otp = getLoginOTP(); if (otp.length !== 6) return toast('Enter 6-digit code', 'error'); const res = await api('/auth/verify-2fa', { method: 'POST', body: JSON.stringify({ otp }) }); if (!res.success) return toast(res.error, 'error'); localStorage.setItem('token', res.auth_token); user = res.user; loginToken = null; $('user-name').textContent = user.username; closeAuth(); showPage('dashboard'); toast('Welcome ' + user.username, 'success') }

$('register-form').onsubmit = async e => { e.preventDefault(); const d = { username: $('reg-user').value, email: $('reg-email').value, password: $('reg-pass').value, role: 'trader' }; const res = await api('/auth/register', { method: 'POST', body: JSON.stringify(d) }); if (!res.success) return toast(res.error, 'error'); regUserId = res.user.user_id; const s = await api('/auth/setup-2fa', { method: 'POST', body: JSON.stringify({ user_id: regUserId, email: d.email }) }); if (!s.success) return toast(s.error, 'error'); $('register-form').classList.add('hidden'); $('2fa-setup').classList.remove('hidden'); $('qr-box').innerHTML = `<img src="${s.qr_code}">`; $('secret-key').textContent = s.secret; $('demo-otp').textContent = s.demo_token; getSetupOTP = setupOTP('setup-otp') };
async function verify2FA() { const otp = getSetupOTP(); if (otp.length !== 6) return toast('Enter 6-digit code', 'error'); const res = await api('/auth/verify-2fa-setup', { method: 'POST', body: JSON.stringify({ user_id: regUserId, otp }) }); if (!res.success) return toast(res.error, 'error'); toast('2FA enabled!', 'success'); showAuth('login') }

const holdings = [{ symbol: 'AAPL', qty: 25, avg: 165, price: 175.50 }, { symbol: 'GOOGL', qty: 15, avg: 135, price: 141.80 }, { symbol: 'MSFT', qty: 10, avg: 350, price: 378.90 }];
function loadDashboard() { const total = holdings.reduce((s, h) => s + h.qty * h.price, 0), cost = holdings.reduce((s, h) => s + h.qty * h.avg, 0); $('portfolio-val').textContent = money(total); $('pnl').textContent = '+' + money(total - cost); $('holdings-table').querySelector('tbody').innerHTML = holdings.map(h => { const v = h.qty * h.price, pnl = (h.price - h.avg) * h.qty; return `<tr><td>${h.symbol}</td><td>${h.qty}</td><td>${money(h.price)}</td><td>${money(v)}</td><td class="${pnl >= 0 ? 'green' : 'red'}">${money(pnl)}</td></tr>` }).join(''); initChart() }
function initChart() { const ctx = $('chart')?.getContext('2d'); if (!ctx) return; new Chart(ctx, { type: 'line', data: { labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], datasets: [{ data: [8000, 8500, 9200, 8800, 10500, 12000], borderColor: '#737373', fill: true, backgroundColor: 'rgba(115,115,115,0.1)', tension: 0.4 }] }, options: { plugins: { legend: { display: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#525252' } }, y: { grid: { color: '#1a1a1a' }, ticks: { color: '#525252' } } } } }) }

const prices = { AAPL: 175.50, GOOGL: 141.80, MSFT: 378.90, TSLA: 248.50 };
function setAction(a) { $('action').value = a; document.querySelectorAll('.action-toggle button').forEach(b => b.classList.remove('active')); document.querySelector(`.action-toggle .${a.toLowerCase()}`).classList.add('active') }
function updateTotal() { $('total').textContent = money((+$('qty').value || 0) * (+$('price').value || 0)) }
$('qty')?.addEventListener('input', updateTotal); $('price')?.addEventListener('input', updateTotal); $('symbol')?.addEventListener('change', () => { $('price').value = prices[$('symbol').value]; updateTotal() });
$('trade-form')?.addEventListener('submit', async e => { e.preventDefault(); if (isLocked()) return toast('Trading locked!', 'error'); const d = { symbol: $('symbol').value, action: $('action').value, quantity: +$('qty').value, price: +$('price').value }; if (user) { const r = await api('/trading/execute', { method: 'POST', body: JSON.stringify(d) }); r.success ? toast(`${d.action} ${d.quantity} ${d.symbol}`, 'success') : toast(r.error, 'error') } else toast(`Demo: ${d.action} ${d.quantity} ${d.symbol}`, 'success') });

function deposit() { toast('Deposited $1000', 'success') }
function withdraw() { toast('Withdrawal requested', 'info') }

function checkLockdown() { const l = JSON.parse(localStorage.getItem('lockdown') || 'null'); if (l && l.until > Date.now()) { applyLockdown(l.until); return true } else if (l) { localStorage.removeItem('lockdown'); removeLockdown() } return false }
function enableLockdown() { const h = parseInt($('lockdown-hours').value) || 1, until = Date.now() + (h * 3600000); localStorage.setItem('lockdown', JSON.stringify({ until })); applyLockdown(until); toast(`Locked for ${h}h`, 'success') }
function applyLockdown(until) { $('lockdown-status').classList.add('active'); $('lockdown-btn').classList.add('hidden'); $('unlock-btn').classList.remove('hidden'); $('lockdown-hours').disabled = true; updateTimer(until); if (lockTimer) clearInterval(lockTimer); lockTimer = setInterval(() => updateTimer(until), 1000); const t = $('trade'); if (t && !t.querySelector('.lockdown-overlay')) { const o = document.createElement('div'); o.className = 'lockdown-overlay'; o.innerHTML = '<i class="fas fa-lock"></i><h3>Trading Locked</h3><p>Lockdown active</p>'; t.querySelector('.trade-grid').style.position = 'relative'; t.querySelector('.trade-grid').appendChild(o) } }
function updateTimer(until) { const r = until - Date.now(); if (r <= 0) return disableLockdown(); const h = Math.floor(r / 3600000), m = Math.floor((r % 3600000) / 60000), s = Math.floor((r % 60000) / 1000); $('lockdown-status').textContent = `${h}h ${m}m ${s}s remaining` }
function disableLockdown() { localStorage.removeItem('lockdown'); removeLockdown(); toast('Unlocked', 'info') }
function removeLockdown() { if (lockTimer) { clearInterval(lockTimer); lockTimer = null } $('lockdown-status')?.classList.remove('active'); $('lockdown-btn')?.classList.remove('hidden'); $('unlock-btn')?.classList.add('hidden'); const h = $('lockdown-hours'); if (h) h.disabled = false; document.querySelectorAll('.lockdown-overlay').forEach(o => o.remove()) }
function isLocked() { const l = JSON.parse(localStorage.getItem('lockdown') || 'null'); return l && l.until > Date.now() }

document.querySelectorAll('.demo-tabs button').forEach(btn => { btn.onclick = () => { document.querySelectorAll('.demo-tabs button').forEach(b => b.classList.remove('active')); document.querySelectorAll('.demo').forEach(d => d.classList.remove('active')); btn.classList.add('active'); $(btn.dataset.tab).classList.add('active') } });
async function demoEncrypt() { let d; try { d = JSON.parse($('enc-input').value || '{}') } catch { d = { msg: 'test' } }; const r = await api('/security/demo/encryption', { method: 'POST', body: JSON.stringify({ data: d }) }); $('enc-output').textContent = r.encrypted ? `Original: ${JSON.stringify(r.original)}\n\nEncrypted: ${r.encrypted.encrypted_data}\nIV: ${r.encrypted.iv}\n\nDecrypted: ${JSON.stringify(r.decrypted.decrypted_data)}` : 'Error' }
async function demoHash() { const p = $('hash-input').value || 'pass123'; const r = await api('/security/demo/hashing', { method: 'POST', body: JSON.stringify({ password: p }) }); $('hash-output').textContent = r.hash_result ? `Password: ${r.password}\n\nHash: ${r.hash_result.hash}\n\nVerify: ${r.verify_correct_password.verified}` : 'Error' }
async function demoSign() { let d; try { d = JSON.parse($('sig-input').value || '{}') } catch { d = { id: '001' } }; const r = await api('/security/demo/signature', { method: 'POST', body: JSON.stringify({ data: d }) }); $('sig-output').textContent = r.signed_trade ? `Data: ${JSON.stringify(r.original_data)}\n\nSignature: ${r.signed_trade.signature}\n\nValid: ${r.verification.signature_valid}` : 'Error' }
async function demoBase64() { let d; try { d = JSON.parse($('b64-input').value || '{}') } catch { d = { text: $('b64-input').value || 'hello' } }; const r = await api('/security/demo/encoding', { method: 'POST', body: JSON.stringify({ data: d }) }); $('b64-output').textContent = r.encoded ? `Original: ${JSON.stringify(r.original)}\n\nEncoded: ${r.encoded.encoded_data}\n\nDecoded: ${JSON.stringify(r.decoded.decoded_data)}` : 'Error' }
async function demoDH() { const r = await api('/security/demo/key-exchange', { method: 'POST' }); $('dh-output').textContent = r.server_public_key ? `Algorithm: ${r.algorithm}\nKey: ${r.key_size}-bit\n\n${r.server_public_key.substring(0, 120)}...\n\nSession: ${r.session_id}` : 'Error' }

document.addEventListener('DOMContentLoaded', async () => { const t = localStorage.getItem('token'); if (t) { const r = await api('/auth/me'); if (r.success) { user = r.user; $('user-name').textContent = user.username; showPage('dashboard') } else localStorage.removeItem('token') } checkLockdown(); $('tx-table').querySelector('tbody').innerHTML = '<tr><td>Jan 31</td><td>Deposit</td><td class="green">+$5,000</td><td>Done</td></tr><tr><td>Jan 30</td><td>Buy AAPL</td><td class="red">-$1,755</td><td>Done</td></tr><tr><td>Jan 29</td><td>Sell TSLA</td><td class="green">+$1,242</td><td>Done</td></tr>' });
